



db:
  host: db
  port: 5432
  user: postgres
  password: postgres
  name: userdb
  sslmode: disable
  pathconfig: "config4.json"



yoomoney:
  base_url: "yoomoney.ru"
  base_path: "quickpay/confirm"
  receiver:
    account: "4100116261841562"
    notification_secret: "Kr3E8Gsh4Jh6MYESOGYXAlXs"